# Generated by Django 4.2.10 on 2025-05-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_private_project',
            field=models.IntegerField(default=0),
        ),
    ]
