# Generated by Django 4.2.10 on 2025-05-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_public_private_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='architect',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='builder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
